### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by SamoilenkoLev** [yandex-money/yandex-checkout-sdk-python#15]
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import yandex_checkout
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/buht/_projects/imperia/local/lib/python2.7/site-packages/yandex_checkout/__init__.py", line 12, in <module>
    from yandex_checkout.domain.notification.webhook_notification import WebhookNotification
  File "/home/buht/_projects/imperia/local/lib/python2.7/site-packages/yandex_checkout/domain/notification/webhook_notification.py", line 1, in <module>
    from yandex_checkout import RefundResponse
ImportError: cannot import name RefundResponse

**Comment by ostulov** [comment]
Спасибо за обращение, исправим.

**Comment by halturin** [comment]
Just created pull request to speed up the process :)

**Comment by eightyeight** [comment]
#16
